CREATE DATABASE SpMedGroup;
GO

USE SpMedGroup;
GO

CREATE TABLE Clinica (
	IdClinica				INT PRIMARY KEY IDENTITY,
	NomeClinica				VARCHAR(200) NOT NULL UNIQUE,
	HorarioComeço			TIME NOT NULL,
	HorarioTermino			TIME NOT NULL,
	CNPJ					VARCHAR(20) NOT NULL,
	RazaoSocial				VARCHAR(200) NOT NULL
);
GO

CREATE TABLE TipoUsuario (
	IdTipoUsuario		INT PRIMARY KEY IDENTITY,
	TituloTipoUsuario	VARCHAR(20) NOT NULL
);
GO

CREATE TABLE Especialidade (
	IdEspecialidade		INT PRIMARY KEY IDENTITY,
	NomeEspecialidade	VARCHAR(200) NOT NULL UNIQUE
);
GO

CREATE Table Usuario (
	IdUsuario		INT PRIMARY KEY IDENTITY,
	NomeUsuario		VARCHAR(200) NOT NULL,
	Email			VARCHAR(200) NOT NULL UNIQUE,
	Senha			VARCHAR(200) NOT NULL,
	DataNasc		DATE,
	Telefone		VARCHAR(200) NOT NULL,
	RG				VARCHAR(200) NOT NULL UNIQUE,
	CPF				VARCHAR(200) NOT NULL UNIQUE,
	IdTipoUsuario	INT FOREIGN KEY REFERENCES TipoUsuario (IdTipoUsuario) NOT NULL
);
GO 

CREATE TABLE Medico (
	IdMedico			INT PRIMARY KEY IDENTITY,
	CRM					VARCHAR(200) NOT NULL UNIQUE,
	IdEspecialidade		INT FOREIGN KEY REFERENCES Especialidade (IdEspecialidade) NOT NULL,
	IdUsuario			INT FOREIGN KEY REFERENCES Usuario (IdUsuario) NOT NULL,
	IdClinica			INT FOREIGN KEY REFERENCES Clinica (IdClinica) NOT NULL,
);
GO

CREATE TABLE Prontuario (
	IdProntuario	INT PRIMARY KEY IDENTITY,
	Descricao		VARCHAR(500) NOT NULL,
	IdClinica		INT FOREIGN KEY REFERENCES Clinica (IdClinica) NOT NULL,
	IdUsuario		INT FOREIGN KEY REFERENCES Usuario (IdUsuario) NOT NULL
);
GO

CREATE TABLE Consulta (
	IdConsulta		INT PRIMARY KEY IDENTITY,
	DataConsulta	DATETIME NOT NULL,
	Descricao		VARCHAR(500) NOT NULL,
	Situacao		VARCHAR(20) NOT NULL,
	IdProntuario	INT FOREIGN KEY REFERENCES Prontuario (IdProntuario) NOT NULL,
	IdMedico		INT FOREIGN KEY REFERENCES Medico (IdMedico) NOT NULL
);
GO

CREATE TABLE Endereco (
	IdEndereco		INT PRIMARY KEY IDENTITY,
	Rua				VARCHAR(200) NOT NULL,
	Numero			VARCHAR(200) NOT NULL,
	Bairro			VARCHAR(200) NOT NULL,
	Cidade			VARCHAR(200) NOT NULL,
	Estado			VARCHAR(200) NOT NULL,
	Complemento		VARCHAR(200),
	IdClinica		INT FOREIGN KEY REFERENCES Clinica (IdClinica),
	IdUsuario		INT FOREIGN KEY REFERENCES Usuario (IdUsuario)
);
GO